### ISSUE TITLE
Suggestion - extend options with prettifyrc file options

### ISSUE THREAD

**Issue by doowb** [jonschlinkert/grunt-prettify#1]
I would suggest extending the options object instead of overwriting it with the prettifyrc file options. This is just because you already setup the defaults before this...

[current code](https://github.com/jonschlinkert/grunt-prettify/blob/master/tasks/prettify.js#L31)

```
options = grunt.file.readJSON(options.prettifyrc);
```

change to

```
options = grunt._.extend(options, grunt.file.readJSON(options.prettifyrc));
```

If you're intending to override the options completely, then you have the correct code.

**Comment by jonschlinkert** [comment]
thanks! I forgot about that.

**Comment by jonschlinkert** [comment]
btw, I think it's `grunt.util._.extend`
