### ISSUE TITLE
Trouble setting inline JS to stay unformatted

### ISSUE THREAD

**Issue by teodragovic** [jonschlinkert/grunt-prettify#11]
I have some inline javascript inside my HTML that I want to keep condensed so I set this options in my grunt file

```
        options: {
            indent: 1,
            indent_char: '  ',
            condense: true,
            brace_style: 'collapse',
            indent_scripts: 'normal',
            unformatted: ['script', 'code', 'pre'],
        }
```

but code inside `<script>` tags still comes out "beautified". 
Is this normal intended behavior or bug and is it possible to get it the way I want?

**Comment by jonschlinkert** [comment]
This is a [js-beautify](https://github.com/einars/js-beautify) issue, mind taking this over there?

**Comment by teodragovic** [comment]
Found the problem in their code and opened an issue https://github.com/einars/js-beautify/issues/383

**Comment by jonschlinkert** [comment]
:+1: Great! I noticed the issue myself after you mentioned it, thanks for letting me know!
