### ISSUE TITLE
css psuedo selectors incorrectly formatted

### ISSUE THREAD

**Issue by codekipple** [jonschlinkert/grunt-prettify#12]
psuedo selectors like this:-

```
a:visited {}
body:after {}
```

Become this:-

```
a: visited {}
body: after {}
```

Which stops the css from working.

**Comment by jonschlinkert** [comment]
Yes, this is a bug with [js-beautify](https://github.com/einars/js-beautify) that I would like to see resolved as well. Please create the issue there, I'll track progress

**Comment by codekipple** [comment]
Ah sorry i didn't realise. Looks like a few people have already raised the issue 
https://github.com/einars/js-beautify/issues/346
https://github.com/einars/js-beautify/issues/339

**Comment by jonschlinkert** [comment]
no prob!
