### ISSUE TITLE
Preserve code inside a php block

### ISSUE THREAD

**Issue by fcalderan** [jonschlinkert/grunt-prettify#14]
I'm trying to prettify a `.php` file containing some php blocks and markup. When I run the prettify task also the php code is "beautified" causing a php error.

Is there a way to preserve the code contained inside

```
<?php
...
?>
```

block? I tried to set `unformatted: ["?php"]` but of course it doesn't work
Thank you

**Comment by jonschlinkert** [comment]
sorry, I don't really have any control over the parser itself. you'll have to create an issue with js-beautify, this is just a grunt task for that lib.
