### ISSUE TITLE
Read `.editorconfig` by default

### ISSUE THREAD

**Issue by ixisio** [jonschlinkert/grunt-prettify#17]
a suggestion would be to read the syntax conventions of a project from the `.editorconfig` file, might be worth....

**Comment by lhwparis** [comment]
+1 for this!

**Comment by jonschlinkert** [comment]
so basically, if a `.editorconfig` file exists in a project, then use the conventions in that as a starting point for the settings?

**Comment by lhwparis** [comment]
yes, and for example that you can extend it with your .jsbeautifyrc file. i realy like to not have 2 different files for defining indent style indent size and so on.

**Comment by ixisio** [comment]
@jonschlinkert 

> so basically, if a .editorconfig file exists in a project, then use the conventions in that as a starting point for the settings?

yeah, `.editorconfig` file could be a good starting point. So, if you do not specify `indent_size` for example in your `.jsbeautifyrc` or Gruntfile, it will use the the Editorconfig entry for that property.

**Comment by ixisio** [comment]
would that be useful for the project in general?
or feels a bit over-engineered?

**Comment by jonschlinkert** [comment]
okay, do you want to write up some requirements to describe how properties in `.editorconfig` would map over to the options in prettify?

**Comment by ixisio** [comment]
yes of course, 'll take care of it as soon ap..

**Comment by jonschlinkert** [comment]
:+1: if you do that I'll get this implemented, thanks!

**Comment by jonschlinkert** [comment]
actually after thinking about it for a bit, I do think it's a bit over-engineered. I like to implement things that users request - and this seems like a fun one to do, but it's probably too much for this project. thanks for the offer to help though!

**Comment by ixisio** [comment]
> would that be useful for the project in general? or feels a bit over-engineered?

yea, no prob!
