### ISSUE TITLE
Can grunt-prettify remove newlines inside attributes?

### ISSUE THREAD

**Issue by mvujovic** [jonschlinkert/grunt-prettify#19]
For example, can grunt-prettify remove the whitespace between "firstClass" and "secondClass" below:

```
<p class="firstClass
  secondClass">
```

**Comment by mvujovic** [comment]
FYI, I tried:

```
prettify: {
  /*jslint camelcase: false */
  options: {
    condense: true,
    preserve_newlines: false
  },
  dist: {
    expand: true,
    cwd: 'dist/html/',
    ext: '.html',
    src: ['**/*.html'],
    dest: 'dist/html/'
  }
},
```

**Comment by jonschlinkert** [comment]
I just had the same issue on gulp-prettify. I believe this is a js-beautify issue, you might want to search the issues there and see if this has already been reported.

**Comment by mvujovic** [comment]
@jonschlinkert Sounds good. Thanks!

**Comment by jonschlinkert** [comment]
no prob, please reopen this if you find that it's being caused here. thanks
