### ISSUE TITLE
subdirectories

### ISSUE THREAD

**Issue by voam** [jonschlinkert/grunt-prettify#23]
I am trying to use this plugin to walk a directory structure and prettify the files in place. Attempts like this:

``` js
{
  expand: true,
  cwd: 'views/',
  ext: '.dust',
  src: ['views/**/*'],
  dest: 'views/'
}
```

don't work. Is this possible?

**Comment by doowb** [comment]
You have `cwd` in your options which is telling the task where to start looking for files. So you can remove `views/` from `src`.

**Comment by voam** [comment]
Thank you very much. That got things moving forward. This is what I ended up using:
<code>
 {
                    expand: true,
                    cwd: 'views/',
                    ext: '.dust',
                    src: ['*_/_.dust'],
                    dest: 'views/'
            }
</code>
(The double astericks in the src property are not displaying properly).
