### ISSUE TITLE
[improvement] an option to keep blank lines

### ISSUE THREAD

**Issue by fcalderan** [jonschlinkert/grunt-prettify#3]
For readability purposes (especially for html files with a lot of lines of code) I'd really like if I could specify an option to keep all blank lines into the markup. 

Thank you

**Comment by jonschlinkert** [comment]
This also is an issue that has been raised on js-beautify, and it's something I'd like to have resolved as well. I'll link to the issue there when I have a moment. Or you can if you beat me to it...

**Comment by bitwiseman** [comment]
https://github.com/einars/js-beautify/tree/v1.4.0

**Comment by jonschlinkert** [comment]
:+1: great thanks!
