### ISSUE TITLE
Inline JS containing HTML e.g. for underscore template output can't be left 'unformatted'

### ISSUE THREAD

**Issue by gearboxdesign** [jonschlinkert/grunt-prettify#5]
Hi,

Firslty must say its a really useful grunt plugin especially for a modular project I am currently working on, but I have encountered an issue when using html inside script tags. For example if I want the prettifier to ignore script blocks with contain some underscore templates but passing 'script' into the 'unformatted' array does not seem to ignore the block during the minification process.

Any help would be much appreciated!

**Comment by jonschlinkert** [comment]
I think this issue is related to https://github.com/einars/js-beautify more than this plugin, since all we're doing is passing in the options from the lib. would you mind creating the issue over there? (probably search first to see if the issue already exists).
