### ISSUE TITLE
"ext" option ignores original filename and replaces extensions incorrectly.

### ISSUE THREAD

**Issue by d9su** [jonschlinkert/grunt-prettify#8]
I have a directory of html files named something like "1.0-my-page.html", basically with a version number in front and name follows separated with dashes. And I am using the prettifier as shown below:

```
prettify: {
            options: {
                // Task-specific options go here.
            },
            pages: {
                expand: true,
                cwd: 'build/html/',
                ext: '.html',
                src: ['*.html'],
                dest: 'build/html/'
            },
        }
```

The above however results in the output being a list of html files named something like "1.html" with the content of every original files named 1.*.html concatenated inside. Same with "2.html" and so on. Getting rid of the "ext" option fixes this.

I think the "ext" option only looks at the first dot and replaces everything after with the extension specified, while it should instead look at the last dot in the filename.

**Comment by jonschlinkert** [comment]
Thanks for the heads up, I'll look into it

**Comment by jonschlinkert** [comment]
Yes, unfortunately this is a Grunt issue. When I read this I couldn't remember if this task was doing something special to extensions, but it's not. My suggestion is to create an issue with Grunt, you might want to search for existing issues about this first though. 

However, I have seen this issue before and although I usually avoid making suggestions about how people write their code, I suggest that you not use a dot in your file names if you want consistent results. Of course, that's up to you. But even if you get it to work with Grunt, don't expect it to work with other modules.

**Comment by d9su** [comment]
Thanks for the follow up @jonschlinkert, I guess I'll adhere to the convention implied by Grunt then, if it's in Grunt fixing it probably won't be worth the while since there might be other modules who imply the same.
