### ISSUE TITLE
Prettify is adding BOM

### ISSUE THREAD

**Issue by jnobbe** [jonschlinkert/grunt-prettify#9]
I have this task set to run after I make a save. I noticed that on one of my pages there were spaces popping up that should not be there. After running a diff I noticed the addition of some U+FEFF characters. I believe Prettify is the cause.

I'm using Grunt v0.4.1, grunt-contrib-watch v0.5.3,and grunt-prettify v0.2.7. Let me know if there is any other information I can provide, or if I am in error.

**Comment by jnobbe** [comment]
…and here is my Gruntfile as well:

```
'use strict';
module.exports = function(grunt) {
    grunt.initConfig({
        // Prettify HTML
        prettify : {
            options : {
                condense              : true,
                padcomments           : false,
                indent                : 4,
                indent_char           : ' ',
                indent_scripts        : 'normal',
                indent_inner_html     : false,
                brace_style           : 'end-expand',
                wrap_line_length      : 0,
                preserve_newlines     : false,
                max_preserve_newlines : 'unlimited',
                unformatted           : ['textarea', 'a', 'strong', 'em', 'span', 'sup', 'img']
            },
            all : {
                expand : true,
                cwd    : './',
                ext    : '.html',
                src    : '**/*.html',
                dest   : './'
            }
        },
        // watch our project for changes
        watch : {
            options : {
                livereload : true,
                nospawn    : true
            },
            html : {
                files   : [ '**/*.html' ],
                tasks   : ['prettify'],
            },
            livereload : {
                files : ['**/*.html', '**/*.{png,jpg,jpeg,gif}']
            }
        }
    });

    // load tasks
    grunt.loadNpmTasks('grunt-contrib-jshint');
    grunt.loadNpmTasks('grunt-prettify');
    grunt.loadNpmTasks('grunt-contrib-watch');

    // register task
    grunt.registerTask('default', ['prettify', 'watch']);

    grunt.event.on('watch', function(action, filepath) {
        grunt.config('prettify.all.src', filepath);
  });
};
```

**Comment by jonschlinkert** [comment]
Thanks for reporting this. It's strange though, I've never had this show up on my files, what OS are you on? It would be easy enough to use iconv-lite to strip the BOM when files are written to disk, I'll look into it further.

**Comment by jnobbe** [comment]
I'm on Mavericks, and I'm also using Sublime 3 if that helps (although this is after Sublime is done with the file).

**Comment by jonschlinkert** [comment]
After looking into this more, I don't think it's this task that is adding the BOM, particularly since grunt methods are being used to read and write the files (https://github.com/gruntjs/grunt/blob/master/lib/grunt/file.js#L228-L234). 

However, I added a preserveBOM option just in case. Let me know if this makes any difference for you, as I wasn't sure how to test this.

I'm closing for now, but please reopen if this is still a problem for you.

**Comment by jnobbe** [comment]
Looking good so far, thank you for looking into this.

**Comment by jonschlinkert** [comment]
:+1:
